export const refs = {
  mainContainer: document.querySelector('.js-main-container'),
  mainContainerLib: document.querySelector('.js-main-container-library'),
  gallery: document.querySelector('.js-movie-gallery'),
  galleryLib: document.querySelector('.js-movie-gallery-library'),
  searchBtn: document.querySelector('.search__form'),
  errorString: document.querySelector('.p__header'),
  footer: document.querySelector('footer'),
  container: document.getElementById('pagination'),
  backdropEl: document.querySelector('.backdrop'),
  filmCardEl: document.querySelector('.modal__container'),
  closeBtnEl: document.querySelector('.modal-btn-close'),
  watchedBtnLib: document.querySelector('.js__btn--watched'),
  quereBtnLib: document.querySelector('.js__btn--quere'),
  scrollButton: document.querySelector('.scroll-js'),
  rocketTail: document.querySelector('.rocket-tail'),
};
