import './js/refs';
import './js/fetch';
import './js/modal';
import './js/searchFilms.js';
import './js/loading';
import './js/pagination';
import './js/local-storage';
import './js/top-page';
import './js/screen-theme';
